### ISSUE TITLE
Surrogates in \u escaped form should be illegal

### ISSUE THREAD

**Issue by eugenesvk** [bgotink/kdl#8]
In v2 this should fail (reges for them is `surrogates := [dD][8-9a-fA-F]hex-digit{2}`)

> Unicode Escape | \u{(1-6 hex chars)} | Code point described by hex characters, as long as it represents a Unicode Scalar Value

```js
const my_doc_str = (String.raw`
no "Surrogtates high\u{D800}\u{D911}\u{DABB}\u{DBFF} low\u{DC00}\u{DEAD}\u{DFFF}"
`);
p(my_doc_str)
const doc1 = parse(my_doc_str)
p(doc1)
```

**Comment by bgotink** [comment]
Ah, didn't catch that one in the spec, thanks!

**Comment by eugenesvk** [comment]
It was contradictory worded in the spec and not explicit in the grammar
